# backend:
#   name: git-gateway
#   repo: 
#   branch: main # Branch to update (optional; defaults to master)

# media_folder: static/img
# public_folder: /img

# collections:
#   - name: 'blog'
#     label: 'Blog'
#     folder: 'content/blog'
#     create: true
#     slug: 'index'
#     media_folder: ''
#     public_folder: ''
#     path: '{{title}}/index'
#     editor:
#       preview: false
#     fields:
#       - { label: 'Title Image', name: title-image, widget: 'image'}
#       - { label: 'Title', name: 'title', widget: 'string' }
#       - { label: 'Publish Date', name: 'date', widget: 'datetime' }
#       - { label: 'Description', name: 'description', widget: 'string' }
#       - { label: 'Body', name: 'body', widget: 'markdown' }
#   - name: 'podcast'
#     label: 'Podcast'
#     folder: 'content/podcast'
#     create: true
#     slug: 'index'
#     media_folder: ''
#     public_folder: ''
#     path: '{{title}}/index'
#     editor:
#     preview: false
#     fields:
#       - { label: 'Title Image', name: title-image, widget: 'image'}
#       - { label: 'Title', name: 'title', widget: 'string' }
#       - { label: 'Publish Date', name: 'date', widget: 'datetime' }
#       - { label: 'Description', name: 'description', widget: 'string' }
#       - { label: 'Body', name: 'body', widget: 'markdown' }